steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - data_ingestion_function
      - --region=asia-east1
      - --runtime=python311
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=main
      - --source=.
      - --memory=512M
      - --gen2
