steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - data_ingestion_function
      - --region=asia-east1
      - --source=.
      - --trigger-http
      - --runtime=python311
